### ISSUE TITLE
Problem when updating 2nd user 

### ISSUE THREAD

**Issue by rdiazroman** [rdiazroman/wordgame#1]
If we have more than one user, (e.g. two) there's a problem when updating the score of the second one. 

`Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:344:11)
    at ServerResponse.header (/Users/rubendiazroman/projects/wordgame/node_modules/express/lib/response.js:718:10)
    at ServerResponse.send (/Users/rubendiazroman/projects/wordgame/node_modules/express/lib/response.js:163:12)
    at ServerResponse.json (/Users/rubendiazroman/projects/wordgame/node_modules/express/lib/response.js:249:15)
    at /Users/rubendiazroman/projects/wordgame/app/routes.js:18:13
    at Query.<anonymous> (/Users/rubendiazroman/projects/wordgame/node_modules/mongoose/lib/model.js:3343:16)
    at /Users/rubendiazroman/projects/wordgame/node_modules/mongoose/node_modules/kareem/index.js:244:21
    at /Users/rubendiazroman/projects/wordgame/node_modules/mongoose/node_modules/kareem/index.js:127:16
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)`

**Comment by rdiazroman** [comment]
Fixed
